# Generated by Django 5.1.7 on 2025-03-22 06:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_vitals', models.JSONField()),
                ('medical_history', models.JSONField()),
                ('current_condition', models.TextField()),
                ('prescribed_medicines', models.JSONField()),
                ('lab_tests', models.JSONField()),
                ('followup_date', models.DateField()),
                ('doctor_details', models.JSONField()),
                ('hospital_details', models.JSONField()),
                ('insurance_details', models.JSONField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patientinfo')),
            ],
        ),
    ]
